# fly.toml app configuration file generated for boost-export-proxy on 2026-04-22T14:05:48+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'boost-export-proxy'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 200
    soft_limit = 100

  [[http_service.checks]]
    interval = '30s'
    timeout = '3s'
    grace_period = '5s'
    method = 'GET'
    path = '/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
